---
title: "sbb_models"
author: "Siyu"
date: "1/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R packages

```{r, message=FALSE}
library(eplusr)
library(tidyverse)
library(ggplot2)
library(here)
library(lubridate)
library(stringr)
library(fs)
library(purrr)
library(data.table)
library(psychrolib)
library(plotly)
library(frost)

for (f in fs::dir_ls(here("fun"), glob = "*.R")) source(f)

options(datatable.print.class = TRUE)
```
## Initialize the simulation model

```{r}
M1 <- read_idf(here("data", "idf", "design_decision", "M1_specs.idf"))
M2 <- read_idf(here("data", "idf", "design_decision", "M2_ufactor.idf"))
M3 <- read_idf(here("data", "idf", "design_decision", "M3_ufactor_infiltration.idf"))
M4 <- read_idf(here("data", "idf", "design_decision", "M4_CHTC.idf"))
M5 <- read_idf(here("data", "idf", "design_decision", "M5_HVAC.idf"))
M6 <- read_idf(here("data", "idf", "design_decision", "M6_HVAC_EMS.idf"))
# ------------------------------------------------------------------------------
# extract IDF data
location_dt <- M6$to_table(class = "Site:Location", wide = TRUE, string_value = FALSE)

# data modification
# data[ , `:=` (y1 = y1, y2 = y2)]
location_dt[ , `:=` (name = "CHICAGO_IL_USA", Name = "CHICAGO_IL_USA", Latitude = 41.78, Longitude = -87.75, `Time Zone` = -6, Elevation = 190)]
# ------------------------------------------------------------------------------
# update object using the tidy table
M6$update(dt_to_load(location_dt))

# update object using FUNCTION set
M6$set(
  Run_Period_1 = list(name = "Run_Period_1", ..2 = 1, ..3 = 1, ..4 = 2021, ..5 = 12, ..6 = 31, ..7 = 2021, ..8 = "Friday")
  )

M6$set(
  People_Room3 = list(name = "People_Room3", ..2 = "Room3", ..3 = "Schcmpt_Occupancy", ..4 = "People", ..5 = 4L, ..6 = "", ..7 = "", ..8 = 0.3, ..9 = "", ..10 = "Schcmpt_Activity")
  )

M6$set(
  Lights_Room3 = list(name = "Lights_Room3", ..2 = "Room3", ..3 = "Schcmpt_Light", ..4 = "LightingLevel", ..5 = 892, ..6 = "", ..7 = "", ..8 = "", ..9 = 0.59, ..10 = 0.2, ..11 = 1, ..12 = "Lights")
  )

M6$set(
  ElecEquip_Room3 = list(name = "ElecEquip_Room3", ..2 = "Room3", ..3 = "Schcmpt_Equipment", ..4 = "EquipmentLevel", ..5 = 530, ..6 = "", ..7 = "", ..8 = "", ..9 = 0.3, ..10 = "", ..11 = "Equipment")
  )
# ------------------------------------------------------------------------------
# Save the modified model
M1$save(here("data", "idf", "design_decision", "M1_specs_1.idf"))
M2$save(here("data", "idf", "design_decision", "M2_ufactor_1.idf"))
M3$save(here("data", "idf", "design_decision", "M3_ufactor_infiltration_1.idf"))
M4$save(here("data", "idf", "design_decision", "M4_CHTC_1.idf"))
M5$save(here("data", "idf", "design_decision", "M5_HVAC_1.idf"))
M6$save(here("data", "idf", "design_decision", "M6_HVAC_EMS_1.idf"))

```


## Model prediction performance for the passive strategies

```{r}
# All SunExpWindExp
path_epw <- here("idf", "SGP_Singapore.486980_IWEC.epw")
idf <- read_idf(path_idf)
# create a parametric prototype of given model and weather file
param <- param_job(idf, path_epw)

#####################
#  Create Measures  #
#####################
# create a measure for modifying LPD
# create a measure for modifying wall constructions

# wall_constr <- "concrete wall 1_U3-27"
set_wall <- function (idf, wall_constr = NA) {
    # keep the original if applicable
    if (is.na(wall_constr)) return(idf)
    # extract data of all non transparent surfaces
    wall <- idf$to_table(class = "BuildingSurface:Detailed", wide = TRUE, string_value = FALSE)
    # modify wall construction
    wall[`Surface Type` == "Wall", `Construction Name` := wall_constr]
    # update object using the tidy table
    idf$update(dt_to_load(wall))
    # return the modified model
    idf
}


set_window <- function (idf, win_constr = NA) {
    # keep the original if applicable
    if (is.na(win_constr)) return(idf)
    # extract data of all non transparent surfaces
    fenes <- idf$to_table(class = "FenestrationSurface:Detailed", wide = TRUE, string_value = FALSE)
    # modify wall construction
    fenes[`Surface Type` == "Window", `Construction Name` := win_constr]
    # update object using the tidy table
    idf$update(dt_to_load(fenes))
    # return the modified model
    idf
}

# set_window <- function (idf, win_constr = NA) {
#     # keep the original if applicable
#     if (is.na(win_constr)) return(idf)
#     # set 'Construction Name' in all 'FenestrationSurface:Detailed' objects
#     idf$set(`FenestrationSurface:Detailed` := list(construction_name = win_constr))
#     # return the modified model
#     idf
# }


set_lpd <- function (idf, lpd = NA) {
    # keep the original if applicable
    if (is.na(lpd)) return(idf)
    # set 'Watts per Zone Floor Area' in all 'Lights' objects as input LPD
    idf$set(Lights := list(watts_per_zone_floor_area = lpd))
    # return the modified model
    idf
}


set_SAT <- function (idf, sat = NA) {
    # keep the original if applicable
    if (is.na(sat)) return(idf)
    # set 'Watts per Zone Floor Area' in all 'Lights' objects as input LPD
    idf$set(`Sizing:Zone` := list(zone_cooling_design_supply_air_temperature = sat))
    idf$set(`Sizing:System` := list(central_cooling_design_supply_air_temperature = sat))
    # return the modified model
    idf
}

# combine three measures into one
ecm <- function (idf, win_constr) {
    idf %>% set_window(win_constr)
}

# ecm <- function (idf, sat) {
#     idf %>% set_SAT(sat)
# }

# ecm <- function (idf, wall_constr, win_constr, lpd) {
#     idf %>% set_wall(wall_constr) %>% set_window(win_constr) %>% set_lpd(lpd)
# }

####################
#  Apply Measures  #
####################
# apply measures and create parametric models
param$apply_measure(ecm,
                    # wall_constr = c("concrete wall 2_U1-16", "concrete wall 3_U0-71", "concrete wall 5_U0-40"),
                    win_constr = c(
                        "Interior_Window",
                        "Dbl Clr 3mm/13mm Air - 1009",
                        # "Dbl Green 3m/6mm Air - 1008",
                        # "Dbl Grey 3mm/13mm Air - 1007",
                        "Dbl LoE (e2=.1) Clr 6mm/13mm Air - 1005",
                        "Dbl LoE Spec Sel Clr 3mm/13mm/6mm Air - 1004",
                        "Dbl LoE Spec Sel Tint 6mm/13mm Air - 1003",
                        # "Dbl Ref-A-H 6mm/13mm Air - 1002",
                        "SageGlass Climaplus Green No Tint - 1001"),
                    # lpd = c(0.2, 0.6, 1),

                    # name of each case
                    .names = c("baseline",
                               "double_cl",
                               # "double_green",
                               # "double_grey",
                               "double_lowE",
                               "double_lowE_spec_sel",
                               "double_lowE_spec_sel_tint",
                               # "double_ref",
                               "SageGlass_green")
)


# param$apply_measure(ecm,
#                     # wall_constr = c("concrete wall 2_U1-16", "concrete wall 3_U0-71", "concrete wall 5_U0-40"),
#                     sat = c(12, 13, 14, 15, 16),
#
#                     # name of each case
#                     .names = c("sat_12",
#                                "sat_13",
#                                "sat_14",
#                                "sat_15",
#                                "sat_16")
# )

# run parametric simulations in parallel
param$run()

# Output End Uses
param_end_use <- param$tabular_data(table_name = "End Uses", wide = TRUE)[[1L]]
param_end_use_dt <- data.table(param_end_use)
fwrite(param_end_use_dt, file = here("data", "model5_SunExpWindExp_IWEC_WWR50.csv"))

# Output report data
param_report_data <- param$report_data(key_value = c("Environment", "ROOM3", "ROOM3 IDEAL LOADS AIR SYSTEM"),
                                   name = c(
                                       "Site Outdoor Air Drybulb Temperature",
                                       "Zone Mean Air Temperature",
                                       "Zone Ideal Loads Supply Air Total Cooling Rate"), wide = TRUE)

fwrite(param_report_data, file = here("data", "report_data_model5_SunExpWindExp_IWEC_WWR50.csv"))
# ------------------------------------------------------------------------------
```


